import type { ReactNode } from 'react';

import type { Metadata } from 'next';

import './globals.css';

const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const RootLayout = ({ children }: { children: ReactNode }): ReactNode => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
export { metadata };
